import type { Database } from '@vidsnapai/database';
import type {
  ReelProductionPlan,
  ReelAsset,
  VoiceProvider,
  VoiceConfiguration,
  VoiceOption,
  StorageProvider
} from '@vidsnapai/types';
import { ReelAssetRepository } from '@vidsnapai/media';
import { LocalStorageProvider } from '@vidsnapai/storage';
import { ConfigurableVoiceProvider } from './voiceProvider.js';

export interface GenerateVoiceOptions {
  voiceConfig?: VoiceConfiguration;
  customNarrationText?: string;
}

export class VoiceService {
  private reelAssetRepo: ReelAssetRepository;
  private voiceProvider: VoiceProvider;
  private storageProvider: StorageProvider;

  constructor(
    db: Database,
    options?: {
      voiceProvider?: VoiceProvider;
      storageProvider?: StorageProvider;
      reelAssetRepo?: ReelAssetRepository;
    }
  ) {
    this.reelAssetRepo = options?.reelAssetRepo || new ReelAssetRepository(db);
    this.voiceProvider = options?.voiceProvider || new ConfigurableVoiceProvider();
    this.storageProvider = options?.storageProvider || new LocalStorageProvider();
  }

  /**
   * Retrieves list of available voices.
   */
  async listAvailableVoices(): Promise<VoiceOption[]> {
    return this.voiceProvider.getVoices();
  }

  /**
   * Synthesizes speech narration for a ReelProductionPlan.
   */
  async generateVoiceTrack(
    reelPlan: ReelProductionPlan,
    workspaceId: string,
    options: GenerateVoiceOptions = {}
  ): Promise<ReelAsset> {
    // 1. Compile narration text
    let narrationText = options.customNarrationText;
    if (!narrationText) {
      if (reelPlan.script && reelPlan.script.length > 0) {
        narrationText = reelPlan.script.map((s) => s.text).join(' ');
      } else if (reelPlan.scenes && reelPlan.scenes.length > 0) {
        narrationText = reelPlan.scenes
          .map((sc) => sc.narration)
          .filter(Boolean)
          .join(' ');
      } else {
        narrationText = reelPlan.narrative || reelPlan.objective || 'Autonomous video narrative.';
      }
    }

    // 2. Resolve Voice Configuration
    const voices = await this.voiceProvider.getVoices();
    const defaultVoice = voices[0] || { id: 'voice-aura-pro-1', name: 'Marcus (Default)' };

    const voiceDirection = reelPlan.voiceDirection || {};
    const gender = (voiceDirection.genderPreference || 'neutral').toLowerCase();
    const matchedVoice = voices.find((v) => v.gender === gender) || defaultVoice;

    const voiceConfig: VoiceConfiguration = options.voiceConfig || {
      voiceId: matchedVoice.id,
      voiceName: matchedVoice.name,
      provider: this.voiceProvider.providerName,
      style: voiceDirection.style || 'Authoritative and dynamic',
      tone: voiceDirection.tone || 'Empowering',
      pace: voiceDirection.pace || 'medium',
      language: voiceDirection.language || 'en-US'
    };

    // 3. Call Voice Provider to Synthesize Speech
    const synthResult = await this.voiceProvider.synthesizeSpeech(
      narrationText,
      voiceConfig
    );

    // 4. Store audio buffer in StorageProvider
    const storageKey = `reels/${reelPlan.id}/voice/voice_${Date.now()}.wav`;
    let uploadUrl = synthResult.audioUrl;

    if (synthResult.audioBuffer) {
      const upload = await this.storageProvider.uploadBuffer(
        synthResult.audioBuffer,
        storageKey,
        'audio/wav',
        `voice_${reelPlan.id.slice(0, 8)}.wav`
      );
      uploadUrl = upload.url;
    }

    // 5. Delete previous voice assets for this reel
    const existingAssets = await this.reelAssetRepo.listByReelPlanId(reelPlan.id);
    const existingVoiceAssets = existingAssets.filter((a: ReelAsset) => a.assetType === 'VOICE');
    for (const eva of existingVoiceAssets) {
      await this.reelAssetRepo.delete(eva.id, workspaceId);
    }

    const config = voiceConfig;

    // 6. Create and persist new ReelAsset record
    return this.reelAssetRepo.create({
      reelPlanId: reelPlan.id,
      workspaceId,
      brandId: reelPlan.brandId,
      sceneNumber: null, // Global reel audio asset
      assetType: 'VOICE',
      sourceType: 'GENERATED',
      provider: this.voiceProvider.providerName,
      providerAssetId: null,
      sourceUrl: uploadUrl,
      previewUrl: uploadUrl,
      storageKey: synthResult.audioBuffer ? storageKey : null,
      filename: `voice_${reelPlan.id.slice(0, 8)}.wav`,
      mimeType: 'audio/wav',
      width: null,
      height: null,
      durationSeconds: synthResult.durationSeconds || reelPlan.durationSeconds,
      metadata: {
        voiceId: config.voiceId,
        voiceName: config.voiceName,
        speed: config.speed,
        pitch: config.pitch,
        style: config.style,
        tone: config.tone,
        language: config.language,
        narrationText
      },
      licenseMetadata: {
        license: 'Generated by VidSnapAI Voice Engine'
      },
      status: 'READY'
    });
  }

  /**
   * Uploads and stores a custom local voice recording/track for a Reel plan.
   */
  async uploadVoiceTrack(
    reelPlan: ReelProductionPlan,
    workspaceId: string,
    file: {
      buffer: Buffer;
      filename: string;
      mimeType: string;
      durationSeconds?: number;
    }
  ): Promise<ReelAsset> {
    const validMimes = [
      'audio/mpeg',
      'audio/mp3',
      'audio/wav',
      'audio/x-wav',
      'audio/m4a',
      'audio/x-m4a',
      'audio/aac',
      'audio/ogg'
    ];

    if (!validMimes.includes(file.mimeType.toLowerCase()) && !file.filename.match(/\.(mp3|wav|m4a|aac|ogg)$/i)) {
      throw new Error(`Unsupported audio format: ${file.mimeType}. Supported formats: MP3, WAV, M4A, AAC, OGG.`);
    }

    const storageKey = `workspaces/${workspaceId}/reels/${reelPlan.id}/audio/voice_upload_${Date.now()}_${file.filename}`;
    const upload = await this.storageProvider.uploadBuffer(
      file.buffer,
      storageKey,
      file.mimeType,
      file.filename
    );

    // Delete existing voice assets
    const existingAssets = await this.reelAssetRepo.listByReelPlanId(reelPlan.id);
    const existingVoiceAssets = existingAssets.filter((a: ReelAsset) => a.assetType === 'VOICE');
    for (const eva of existingVoiceAssets) {
      await this.reelAssetRepo.delete(eva.id, workspaceId);
    }

    return this.reelAssetRepo.create({
      reelPlanId: reelPlan.id,
      workspaceId,
      brandId: reelPlan.brandId,
      sceneNumber: null,
      assetType: 'VOICE',
      sourceType: 'LOCAL_GALLERY',
      provider: 'local_gallery',
      providerAssetId: null,
      sourceUrl: upload.url,
      previewUrl: upload.url,
      storageKey,
      filename: file.filename,
      mimeType: file.mimeType,
      durationSeconds: file.durationSeconds || reelPlan.durationSeconds,
      metadata: {
        isLocalUpload: true,
        sizeBytes: file.buffer.length
      },
      licenseMetadata: {
        license: 'User Uploaded Local Audio'
      },
      status: 'READY'
    });
  }

  /**
   * Alias for uploadVoiceTrack
   */
  async uploadLocalVoiceTrack(
    reelPlan: ReelProductionPlan,
    workspaceId: string,
    file: {
      buffer: Buffer;
      filename: string;
      mimeType: string;
      durationSeconds?: number;
    }
  ): Promise<ReelAsset> {
    return this.uploadVoiceTrack(reelPlan, workspaceId, file);
  }

  /**
   * Retrieves the current voice asset for a Reel plan.
   */
  async getVoiceTrack(reelPlanId: string): Promise<ReelAsset | null> {
    const assets = await this.reelAssetRepo.listByReelPlanId(reelPlanId);
    return assets.find((a: ReelAsset) => a.assetType === 'VOICE' && a.status === 'READY') || null;
  }
}
