import type { ReelStatus } from '@vidsnapai/types';

export class LifecycleValidator {
  private static allowedTransitions: Record<ReelStatus, ReelStatus[]> = {
    DRAFT: ['QUEUED', 'GENERATING', 'READY', 'IN_PRODUCTION', 'GENERATION_FAILED'],
    QUEUED: ['GENERATING', 'IN_PRODUCTION', 'RENDERING', 'FAILED', 'GENERATION_FAILED'],
    GENERATING: ['READY', 'NEEDS_REVIEW', 'IN_PRODUCTION', 'GENERATION_FAILED', 'FAILED'],
    READY: ['IN_PRODUCTION', 'RENDERING', 'COMPLETED', 'APPROVAL_REQUIRED', 'APPROVED', 'RENDER_FAILED', 'FAILED'],
    NEEDS_REVIEW: ['APPROVED', 'REJECTED', 'GENERATING', 'IN_PRODUCTION', 'DRAFT'],
    IN_PRODUCTION: ['RENDERING', 'QUALITY_CHECK', 'RENDERED', 'READY_FOR_APPROVAL', 'COMPLETED', 'APPROVAL_REQUIRED', 'APPROVED', 'REJECTED', 'RENDER_FAILED', 'FAILED'],
    RENDERING: ['QUALITY_CHECK', 'RENDERED', 'READY_FOR_APPROVAL', 'COMPLETED', 'RENDER_FAILED', 'RENDER_QUALITY_FAILED', 'FAILED'],
    RENDERED: ['QUALITY_CHECK', 'READY_FOR_APPROVAL', 'COMPLETED', 'RENDER_QUALITY_FAILED', 'FAILED'],
    QUALITY_CHECK: ['READY_FOR_APPROVAL', 'COMPLETED', 'RENDER_QUALITY_FAILED', 'RENDER_FAILED', 'FAILED'],
    READY_FOR_APPROVAL: ['APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'READY_FOR_ADS', 'IN_PRODUCTION'],
    COMPLETED: ['APPROVAL_REQUIRED', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'READY_FOR_ADS', 'PUBLISHED_TO_META', 'IN_PRODUCTION'],
    APPROVAL_REQUIRED: ['APPROVED', 'REJECTED', 'IN_PRODUCTION', 'GENERATING'],
    APPROVED: ['SCHEDULED', 'PUBLISHED', 'READY_FOR_ADS', 'PUBLISHED_TO_META', 'APPROVAL_REQUIRED', 'REJECTED', 'IN_PRODUCTION', 'ARCHIVED'],
    READY_FOR_ADS: ['PUBLISHED_TO_META', 'PUBLISH_FAILED', 'APPROVED', 'REJECTED', 'ARCHIVED'],
    REJECTED: ['GENERATING', 'IN_PRODUCTION', 'DRAFT', 'APPROVAL_REQUIRED', 'APPROVED'],
    SCHEDULED: ['PUBLISHED', 'PUBLISH_FAILED', 'APPROVED', 'ARCHIVED'],
    PUBLISHED: ['ARCHIVED', 'READY_FOR_ADS', 'PUBLISHED_TO_META'],
    PUBLISHED_TO_META: ['ARCHIVED', 'READY_FOR_ADS'],
    FAILED: ['QUEUED', 'GENERATING', 'IN_PRODUCTION', 'RENDERING', 'DRAFT'],
    GENERATION_FAILED: ['QUEUED', 'GENERATING', 'DRAFT'],
    RENDER_FAILED: ['IN_PRODUCTION', 'RENDERING', 'QUEUED'],
    RENDER_QUALITY_FAILED: ['IN_PRODUCTION', 'RENDERING', 'QUEUED'],
    PUBLISH_FAILED: ['SCHEDULED', 'PUBLISHED', 'READY_FOR_ADS', 'PUBLISHED_TO_META', 'APPROVED'],
    ARCHIVED: ['DRAFT']
  };

  static isValidTransition(currentStatus: ReelStatus, nextStatus: ReelStatus): boolean {
    if (currentStatus === nextStatus) return true;
    const allowed = this.allowedTransitions[currentStatus] || [];
    return allowed.includes(nextStatus);
  }

  static validateTransition(currentStatus: ReelStatus, nextStatus: ReelStatus): void {
    if (!this.isValidTransition(currentStatus, nextStatus)) {
      throw new Error(
        `Invalid reel status transition from "${currentStatus}" to "${nextStatus}".`
      );
    }
  }
}
